### ISSUE TITLE
git conflict marks in master branch

### ISSUE THREAD

**Issue by jenjiyi** [learn-co-students/devise_roles_lab-v-000#96]
Noticed some git conflict marks in config/initializers/devise.rb:175 when I ran rspec after cloning. 

```
<<<<<<< HEAD
  config.reconfirmable = true
=======
  config.reconfirmable = false
>>>>>>> origin/solution 
```

**Comment by gj** [comment]
Fixed here: https://github.com/learn-co-students/devise_roles_lab-v-000/commit/4a9265c90a47253b41d20aba48d17708f631bb42

Thanks @jenjiyi !
